#!/bin/bash

###############################################################################
# Grow Monitoring System - Automatische MQTT Setup
#
# Dieses Script installiert und konfiguriert automatisch:
# - MQTT Broker (Mosquitto)
# - Backend MQTT Konfiguration
# - Verbindungs-Tests
#
# Unterstützte Systeme: Ubuntu/Debian, Raspberry Pi, macOS
###############################################################################

set -e  # Exit bei Fehler

# Farben für Output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Banner
echo -e "${GREEN}"
cat << "EOF"
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║   🌱 Grow Monitoring System - MQTT Automatische Installation ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# Funktionen
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[!]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

# Betriebssystem erkennen
detect_os() {
    log_info "Erkenne Betriebssystem..."

    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if [ -f /etc/os-release ]; then
            . /etc/os-release
            OS=$ID
            VER=$VERSION_ID
            log_success "Erkannt: $PRETTY_NAME"
        else
            log_error "Konnte OS nicht erkennen"
            exit 1
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        OS="macos"
        VER=$(sw_vers -productVersion)
        log_success "Erkannt: macOS $VER"
    else
        log_error "Nicht unterstütztes OS: $OSTYPE"
        exit 1
    fi
}

# Root-Rechte prüfen (für Linux)
check_sudo() {
    if [[ "$OS" != "macos" ]]; then
        if [ "$EUID" -ne 0 ]; then
            log_warn "Dieses Script benötigt sudo-Rechte für die Installation"
            log_info "Führe Script mit sudo aus oder gib dein Passwort ein wenn gefragt"
        fi
    fi
}

# Mosquitto installieren
install_mosquitto() {
    log_info "Installiere Mosquitto MQTT Broker..."

    if [[ "$OS" == "ubuntu" ]] || [[ "$OS" == "debian" ]] || [[ "$OS" == "raspbian" ]]; then
        # Ubuntu/Debian/Raspberry Pi
        sudo apt update
        sudo apt install -y mosquitto mosquitto-clients

    elif [[ "$OS" == "macos" ]]; then
        # macOS mit Homebrew
        if ! command -v brew &> /dev/null; then
            log_error "Homebrew ist nicht installiert. Bitte installiere Homebrew zuerst:"
            echo "  /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
            exit 1
        fi
        brew install mosquitto

    else
        log_error "Automatische Installation für $OS nicht implementiert"
        log_info "Bitte installiere Mosquitto manuell: https://mosquitto.org/download/"
        exit 1
    fi

    log_success "Mosquitto installiert"
}

# Mosquitto konfigurieren
configure_mosquitto() {
    log_info "Konfiguriere Mosquitto..."

    # Backup der Original-Config
    if [[ "$OS" == "macos" ]]; then
        MQTT_CONF="/opt/homebrew/etc/mosquitto/mosquitto.conf"
        MQTT_DIR="/opt/homebrew/etc/mosquitto"
    else
        MQTT_CONF="/etc/mosquitto/mosquitto.conf"
        MQTT_DIR="/etc/mosquitto"
    fi

    if [ -f "$MQTT_CONF" ]; then
        sudo cp "$MQTT_CONF" "${MQTT_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
        log_success "Backup erstellt: ${MQTT_CONF}.backup"
    fi

    # Neue Konfiguration erstellen
    log_info "Erstelle Konfiguration..."

    sudo tee "$MQTT_CONF" > /dev/null << 'MQTTCONF'
# Grow Monitoring System - Mosquitto Configuration
# Auto-generated by setup-mqtt.sh

# Standard MQTT Listener
listener 1883
protocol mqtt

# WebSocket Listener (für Browser-Clients)
listener 9001
protocol websockets

# Authentifizierung (vorerst deaktiviert für einfaches Setup)
allow_anonymous true

# Logging
log_dest file /var/log/mosquitto/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

# Persistence (Nachrichten speichern)
persistence true
persistence_location /var/lib/mosquitto/

# Retained Messages
retained_persistence true
autosave_interval 1800

# Connection Settings
max_connections -1
max_keepalive 65535
MQTTCONF

    log_success "Mosquitto konfiguriert"
}

# Mosquitto Service starten
start_mosquitto() {
    log_info "Starte Mosquitto Service..."

    if [[ "$OS" == "macos" ]]; then
        # macOS
        brew services start mosquitto
    else
        # Linux
        sudo systemctl enable mosquitto
        sudo systemctl start mosquitto
        sleep 2

        # Status prüfen
        if sudo systemctl is-active --quiet mosquitto; then
            log_success "Mosquitto Service läuft"
        else
            log_error "Mosquitto Service konnte nicht gestartet werden"
            log_info "Prüfe Logs: sudo journalctl -u mosquitto -n 50"
            exit 1
        fi
    fi
}

# Port-Verfügbarkeit prüfen
check_port() {
    local port=$1
    log_info "Prüfe Port $port..."

    if command -v netstat &> /dev/null; then
        if netstat -tuln | grep ":$port " > /dev/null 2>&1; then
            log_success "Port $port ist offen"
            return 0
        fi
    elif command -v ss &> /dev/null; then
        if ss -tuln | grep ":$port " > /dev/null 2>&1; then
            log_success "Port $port ist offen"
            return 0
        fi
    fi

    log_warn "Port $port scheint nicht erreichbar zu sein"
    return 1
}

# MQTT-Verbindung testen
test_mqtt_connection() {
    log_info "Teste MQTT-Verbindung..."

    # Prüfe ob mosquitto_sub verfügbar ist
    if ! command -v mosquitto_sub &> /dev/null; then
        log_error "mosquitto_sub nicht gefunden"
        return 1
    fi

    # Test mit Timeout
    log_info "Starte Test-Subscriber..."
    timeout 2 mosquitto_sub -h localhost -t 'test/topic' > /tmp/mqtt_test_sub.log 2>&1 &
    SUB_PID=$!
    sleep 1

    log_info "Sende Test-Nachricht..."
    if mosquitto_pub -h localhost -t 'test/topic' -m 'Hello MQTT!' 2>&1 | grep -q "Error"; then
        log_error "Fehler beim Senden der Test-Nachricht"
        kill $SUB_PID 2>/dev/null || true
        return 1
    fi

    sleep 1
    kill $SUB_PID 2>/dev/null || true

    if grep -q "Hello MQTT!" /tmp/mqtt_test_sub.log 2>/dev/null; then
        log_success "MQTT-Verbindung funktioniert!"
        rm -f /tmp/mqtt_test_sub.log
        return 0
    else
        log_error "MQTT-Test fehlgeschlagen"
        return 1
    fi
}

# IP-Adresse ermitteln
get_ip_address() {
    log_info "Ermittle IP-Adresse..."

    if [[ "$OS" == "macos" ]]; then
        # macOS
        IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "127.0.0.1")
    else
        # Linux
        IP=$(hostname -I | awk '{print $1}' || echo "127.0.0.1")
    fi

    log_success "IP-Adresse: $IP"
    echo "$IP"
}

# Backend .env konfigurieren
configure_backend() {
    log_info "Konfiguriere Backend für MQTT..."

    # Prüfe ob backend/.env existiert
    if [ ! -f "backend/.env" ]; then
        log_warn "backend/.env nicht gefunden"
        if [ -f "backend/.env.example" ]; then
            log_info "Kopiere .env.example zu .env..."
            cp backend/.env.example backend/.env
        else
            log_error "backend/.env.example nicht gefunden!"
            log_info "Bitte erstelle backend/.env manuell"
            return 1
        fi
    fi

    # IP-Adresse ermitteln
    LOCAL_IP=$(get_ip_address)

    # Prüfe ob MQTT-Konfiguration bereits vorhanden
    if grep -q "^MQTT_ENABLED=" backend/.env 2>/dev/null; then
        log_info "MQTT-Konfiguration bereits vorhanden, aktualisiere..."
        sed -i.bak "s|^MQTT_ENABLED=.*|MQTT_ENABLED=true|" backend/.env
        sed -i.bak "s|^MQTT_BROKER_URL=.*|MQTT_BROKER_URL=mqtt://localhost:1883|" backend/.env
    else
        log_info "Füge MQTT-Konfiguration hinzu..."
        cat >> backend/.env << ENVCONF

# MQTT Configuration (Auto-generated by setup-mqtt.sh)
MQTT_ENABLED=true
MQTT_BROKER_URL=mqtt://localhost:1883
MQTT_USERNAME=
MQTT_PASSWORD=
MQTT_BASE_TOPIC=grow_monitoring
MQTT_CLIENT_ID=grow_backend

# Home Assistant Discovery
MQTT_HA_DISCOVERY=true
MQTT_HA_PREFIX=homeassistant
ENVCONF
    fi

    log_success "Backend konfiguriert"
    log_info "MQTT Broker URL: mqtt://localhost:1883"
    log_info "Für externe Zugriffe von ESP32: mqtt://$LOCAL_IP:1883"
}

# Firewall-Regel hinzufügen (falls UFW aktiv)
configure_firewall() {
    if command -v ufw &> /dev/null; then
        if sudo ufw status | grep -q "Status: active"; then
            log_info "UFW Firewall ist aktiv, füge Regeln hinzu..."
            sudo ufw allow 1883/tcp comment 'MQTT Broker'
            sudo ufw allow 9001/tcp comment 'MQTT WebSocket'
            log_success "Firewall-Regeln hinzugefügt"
        fi
    fi
}

# Zusammenfassung anzeigen
show_summary() {
    local IP=$(get_ip_address)

    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                    ✓ Installation abgeschlossen!              ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}MQTT Broker Status:${NC}"
    echo "  • URL (lokal):    mqtt://localhost:1883"
    echo "  • URL (Netzwerk): mqtt://$IP:1883"
    echo "  • WebSocket:      ws://localhost:9001"
    echo "  • Status:         $(systemctl is-active mosquitto 2>/dev/null || echo 'läuft')"
    echo ""
    echo -e "${BLUE}Backend Konfiguration:${NC}"
    echo "  • .env aktualisiert: backend/.env"
    echo "  • MQTT_ENABLED:      true"
    echo "  • MQTT_BROKER_URL:   mqtt://localhost:1883"
    echo ""
    echo -e "${BLUE}Nächste Schritte:${NC}"
    echo "  1. Backend neu starten:"
    echo "     ${YELLOW}cd backend && npm run dev${NC}"
    echo ""
    echo "  2. ESP32 konfigurieren (in ESP32-Code):"
    echo "     ${YELLOW}const char* mqtt_server = \"$IP\";${NC}"
    echo "     ${YELLOW}const int mqtt_port = 1883;${NC}"
    echo ""
    echo "  3. MQTT Explorer installieren (Optional):"
    echo "     http://mqtt-explorer.com/"
    echo ""
    echo -e "${BLUE}MQTT testen:${NC}"
    echo "  # Terminal 1: Subscribe"
    echo "  ${YELLOW}mosquitto_sub -h localhost -t 'grow_monitoring/#' -v${NC}"
    echo ""
    echo "  # Terminal 2: Publish"
    echo "  ${YELLOW}mosquitto_pub -h localhost -t 'grow_monitoring/test' -m 'Hello!'${NC}"
    echo ""
    echo -e "${GREEN}Viel Erfolg! 🌱${NC}"
    echo ""
}

# Hauptprogramm
main() {
    # System-Checks
    detect_os
    check_sudo

    echo ""
    log_info "Starte Installation..."
    echo ""

    # Installation
    install_mosquitto
    configure_mosquitto
    start_mosquitto

    # Tests
    sleep 2
    check_port 1883
    check_port 9001
    test_mqtt_connection

    # Konfiguration
    configure_backend
    configure_firewall

    # Zusammenfassung
    show_summary

    exit 0
}

# Script ausführen
main
