# Grow Monitoring System - Automatische MQTT Setup (Windows PowerShell)
#
# Dieses Script installiert und konfiguriert automatisch:
# - MQTT Broker (Mosquitto)
# - Backend MQTT Konfiguration
# - Verbindungs-Tests
#
# WICHTIG: Als Administrator ausführen!

param(
    [switch]$SkipInstall,
    [switch]$ConfigureOnly
)

# Prüfe Admin-Rechte
function Test-IsAdmin {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-IsAdmin)) {
    Write-Host "❌ FEHLER: Dieses Script benötigt Administrator-Rechte!" -ForegroundColor Red
    Write-Host ""
    Write-Host "Bitte führe PowerShell als Administrator aus:" -ForegroundColor Yellow
    Write-Host "  1. PowerShell suchen" -ForegroundColor Cyan
    Write-Host "  2. Rechtsklick → 'Als Administrator ausführen'" -ForegroundColor Cyan
    Write-Host "  3. Script erneut ausführen" -ForegroundColor Cyan
    Write-Host ""
    Read-Host "Drücke Enter zum Beenden"
    exit 1
}

# Banner
Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║                                                               ║" -ForegroundColor Green
Write-Host "║   🌱 Grow Monitoring System - MQTT Automatische Installation ║" -ForegroundColor Green
Write-Host "║                      (Windows PowerShell)                     ║" -ForegroundColor Green
Write-Host "║                                                               ║" -ForegroundColor Green
Write-Host "╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

# Funktionen
function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "[✓] $Message" -ForegroundColor Green
}

function Write-Warning {
    param([string]$Message)
    Write-Host "[!] $Message" -ForegroundColor Yellow
}

function Write-Error {
    param([string]$Message)
    Write-Host "[✗] $Message" -ForegroundColor Red
}

# Mosquitto Installationspfad
$MosquittoPath = "C:\Program Files\mosquitto"
$MosquittoExe = "$MosquittoPath\mosquitto.exe"
$MosquittoConf = "$MosquittoPath\mosquitto.conf"

# Mosquitto installieren
function Install-Mosquitto {
    if ($SkipInstall -or $ConfigureOnly) {
        Write-Info "Installation übersprungen (Parameter)"
        return
    }

    Write-Info "Prüfe ob Mosquitto bereits installiert ist..."

    if (Test-Path $MosquittoExe) {
        Write-Success "Mosquitto ist bereits installiert: $MosquittoPath"
        $response = Read-Host "Möchtest du die Installation überspringen? (J/N)"
        if ($response -eq 'J' -or $response -eq 'j') {
            return
        }
    }

    Write-Info "Mosquitto wird heruntergeladen..."
    Write-Warning "WICHTIG: Bitte lade Mosquitto manuell herunter und installiere es:"
    Write-Host ""
    Write-Host "  1. Öffne: https://mosquitto.org/download/" -ForegroundColor Cyan
    Write-Host "  2. Lade 'mosquitto-X.X.X-install-windows-x64.exe' herunter" -ForegroundColor Cyan
    Write-Host "  3. Führe den Installer aus" -ForegroundColor Cyan
    Write-Host "  4. Installiere mit Standard-Optionen" -ForegroundColor Cyan
    Write-Host "  5. Komme zurück zu diesem Script" -ForegroundColor Cyan
    Write-Host ""

    $response = Read-Host "Hast du Mosquitto installiert? (J/N)"
    if ($response -ne 'J' -and $response -ne 'j') {
        Write-Error "Installation abgebrochen"
        exit 1
    }

    if (-not (Test-Path $MosquittoExe)) {
        Write-Error "Mosquitto wurde nicht gefunden in: $MosquittoPath"
        Write-Info "Stelle sicher, dass du Mosquitto installiert hast"
        exit 1
    }

    Write-Success "Mosquitto gefunden!"
}

# Mosquitto konfigurieren
function Configure-Mosquitto {
    Write-Info "Konfiguriere Mosquitto..."

    # Backup der Original-Config
    if (Test-Path $MosquittoConf) {
        $backupFile = "$MosquittoConf.backup.$(Get-Date -Format 'yyyyMMdd_HHmmss')"
        Copy-Item $MosquittoConf $backupFile
        Write-Success "Backup erstellt: $backupFile"
    }

    # Neue Konfiguration
    $configContent = @"
# Grow Monitoring System - Mosquitto Configuration
# Auto-generated by setup-mqtt.ps1

# Standard MQTT Listener
listener 1883
protocol mqtt

# WebSocket Listener (für Browser-Clients)
listener 9001
protocol websockets

# Authentifizierung (vorerst deaktiviert)
allow_anonymous true

# Logging
log_dest file $MosquittoPath\mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

# Persistence
persistence true
persistence_location $MosquittoPath\data\

# Retained Messages
retained_persistence true
autosave_interval 1800

# Connection Settings
max_connections -1
max_keepalive 65535
"@

    # Config-Datei schreiben
    Set-Content -Path $MosquittoConf -Value $configContent -Force
    Write-Success "Mosquitto konfiguriert"

    # Data-Verzeichnis erstellen
    $dataDir = "$MosquittoPath\data"
    if (-not (Test-Path $dataDir)) {
        New-Item -ItemType Directory -Path $dataDir -Force | Out-Null
        Write-Success "Data-Verzeichnis erstellt: $dataDir"
    }
}

# Mosquitto Service starten
function Start-MosquittoService {
    Write-Info "Starte Mosquitto Service..."

    # Prüfe ob Service existiert
    $service = Get-Service -Name "Mosquitto Broker" -ErrorAction SilentlyContinue

    if ($null -eq $service) {
        Write-Warning "Mosquitto Service nicht gefunden"
        Write-Info "Erstelle und starte Service..."

        # Service installieren (falls nicht vorhanden)
        & "$MosquittoPath\mosquitto.exe" install

        Start-Sleep -Seconds 2
        $service = Get-Service -Name "Mosquitto Broker" -ErrorAction SilentlyContinue
    }

    if ($service.Status -ne 'Running') {
        # Service starten
        Start-Service -Name "Mosquitto Broker"
        Start-Sleep -Seconds 3

        # Status prüfen
        $service = Get-Service -Name "Mosquitto Broker"
        if ($service.Status -eq 'Running') {
            Write-Success "Mosquitto Service läuft"
        } else {
            Write-Error "Service konnte nicht gestartet werden: $($service.Status)"
            exit 1
        }
    } else {
        Write-Success "Mosquitto Service läuft bereits"
    }

    # Auto-Start aktivieren
    Set-Service -Name "Mosquitto Broker" -StartupType Automatic
    Write-Success "Auto-Start aktiviert"
}

# Port-Verfügbarkeit prüfen
function Test-Port {
    param([int]$Port)

    Write-Info "Prüfe Port $Port..."

    $connections = Get-NetTCPConnection -LocalPort $Port -ErrorAction SilentlyContinue

    if ($connections) {
        Write-Success "Port $Port ist offen"
        return $true
    } else {
        Write-Warning "Port $Port scheint nicht erreichbar zu sein"
        return $false
    }
}

# Firewall-Regel hinzufügen
function Add-FirewallRule {
    Write-Info "Konfiguriere Windows Firewall..."

    # Prüfe ob Regeln bereits existieren
    $ruleExists = Get-NetFirewallRule -DisplayName "MQTT Broker (1883)" -ErrorAction SilentlyContinue

    if (-not $ruleExists) {
        # Regel für Port 1883
        New-NetFirewallRule -DisplayName "MQTT Broker (1883)" `
            -Direction Inbound `
            -Protocol TCP `
            -LocalPort 1883 `
            -Action Allow `
            -Profile Any `
            -Description "Grow Monitoring System - MQTT Broker" | Out-Null

        Write-Success "Firewall-Regel für Port 1883 hinzugefügt"
    } else {
        Write-Success "Firewall-Regel für Port 1883 existiert bereits"
    }

    # Regel für Port 9001 (WebSocket)
    $ruleExists = Get-NetFirewallRule -DisplayName "MQTT WebSocket (9001)" -ErrorAction SilentlyContinue

    if (-not $ruleExists) {
        New-NetFirewallRule -DisplayName "MQTT WebSocket (9001)" `
            -Direction Inbound `
            -Protocol TCP `
            -LocalPort 9001 `
            -Action Allow `
            -Profile Any `
            -Description "Grow Monitoring System - MQTT WebSocket" | Out-Null

        Write-Success "Firewall-Regel für Port 9001 hinzugefügt"
    } else {
        Write-Success "Firewall-Regel für Port 9001 existiert bereits"
    }
}

# MQTT-Verbindung testen
function Test-MqttConnection {
    Write-Info "Teste MQTT-Verbindung..."

    $mosquittoPub = "$MosquittoPath\mosquitto_pub.exe"
    $mosquittoSub = "$MosquittoPath\mosquitto_sub.exe"

    if (-not (Test-Path $mosquittoPub)) {
        Write-Error "mosquitto_pub.exe nicht gefunden"
        return $false
    }

    # Test-Nachricht senden
    $testTopic = "test/powershell/$(Get-Random)"
    $testMessage = "Hello from PowerShell!"

    try {
        # Subscriber im Hintergrund starten
        $subJob = Start-Job -ScriptBlock {
            param($exe, $topic)
            & $exe -h localhost -t $topic -C 1
        } -ArgumentList $mosquittoSub, $testTopic

        Start-Sleep -Seconds 1

        # Publisher
        & $mosquittoPub -h localhost -t $testTopic -m $testMessage 2>&1 | Out-Null

        # Warte auf Subscriber-Ergebnis
        $result = Wait-Job -Job $subJob -Timeout 5 | Receive-Job

        if ($result -eq $testMessage) {
            Write-Success "MQTT-Verbindung funktioniert!"
            return $true
        } else {
            Write-Error "MQTT-Test fehlgeschlagen (keine Antwort empfangen)"
            return $false
        }
    } catch {
        Write-Error "MQTT-Test fehlgeschlagen: $_"
        return $false
    } finally {
        Remove-Job -Job $subJob -Force -ErrorAction SilentlyContinue
    }
}

# IP-Adresse ermitteln
function Get-LocalIPAddress {
    Write-Info "Ermittle IP-Adresse..."

    $ip = (Get-NetIPAddress -AddressFamily IPv4 |
           Where-Object { $_.IPAddress -notlike "127.*" -and $_.InterfaceAlias -notlike "*Loopback*" } |
           Select-Object -First 1).IPAddress

    if ($ip) {
        Write-Success "IP-Adresse: $ip"
        return $ip
    } else {
        Write-Warning "Konnte IP-Adresse nicht ermitteln, verwende localhost"
        return "127.0.0.1"
    }
}

# Backend .env konfigurieren
function Configure-Backend {
    Write-Info "Konfiguriere Backend für MQTT..."

    $envFile = "backend\.env"
    $envExample = "backend\.env.example"

    # Prüfe ob .env existiert
    if (-not (Test-Path $envFile)) {
        Write-Warning "backend\.env nicht gefunden"
        if (Test-Path $envExample) {
            Write-Info "Kopiere .env.example zu .env..."
            Copy-Item $envExample $envFile
        } else {
            Write-Error "backend\.env.example nicht gefunden!"
            Write-Info "Bitte erstelle backend\.env manuell"
            return $false
        }
    }

    # IP-Adresse ermitteln
    $localIP = Get-LocalIPAddress

    # Lese aktuelle .env
    $envContent = Get-Content $envFile -Raw

    # MQTT-Konfiguration
    $mqttConfig = @"

# MQTT Configuration (Auto-generated by setup-mqtt.ps1)
MQTT_ENABLED=true
MQTT_BROKER_URL=mqtt://localhost:1883
MQTT_USERNAME=
MQTT_PASSWORD=
MQTT_BASE_TOPIC=grow_monitoring
MQTT_CLIENT_ID=grow_backend

# Home Assistant Discovery
MQTT_HA_DISCOVERY=true
MQTT_HA_PREFIX=homeassistant
"@

    # Prüfe ob MQTT-Config bereits vorhanden
    if ($envContent -match "MQTT_ENABLED=") {
        Write-Info "MQTT-Konfiguration bereits vorhanden, aktualisiere..."
        $envContent = $envContent -replace "MQTT_ENABLED=.*", "MQTT_ENABLED=true"
        $envContent = $envContent -replace "MQTT_BROKER_URL=.*", "MQTT_BROKER_URL=mqtt://localhost:1883"
    } else {
        Write-Info "Füge MQTT-Konfiguration hinzu..."
        $envContent += $mqttConfig
    }

    # Schreibe .env
    Set-Content -Path $envFile -Value $envContent -NoNewline

    Write-Success "Backend konfiguriert"
    Write-Info "MQTT Broker URL: mqtt://localhost:1883"
    Write-Info "Für ESP32: mqtt://$localIP:1883"

    return $true
}

# Zusammenfassung
function Show-Summary {
    $ip = Get-LocalIPAddress

    Write-Host ""
    Write-Host "╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
    Write-Host "║                    ✓ Installation abgeschlossen!              ║" -ForegroundColor Green
    Write-Host "╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
    Write-Host ""
    Write-Host "MQTT Broker Status:" -ForegroundColor Cyan
    $service = Get-Service -Name "Mosquitto Broker"
    Write-Host "  • URL (lokal):    mqtt://localhost:1883"
    Write-Host "  • URL (Netzwerk): mqtt://$ip:1883"
    Write-Host "  • WebSocket:      ws://localhost:9001"
    Write-Host "  • Status:         $($service.Status)"
    Write-Host ""
    Write-Host "Backend Konfiguration:" -ForegroundColor Cyan
    Write-Host "  • .env aktualisiert: backend\.env"
    Write-Host "  • MQTT_ENABLED:      true"
    Write-Host "  • MQTT_BROKER_URL:   mqtt://localhost:1883"
    Write-Host ""
    Write-Host "Nächste Schritte:" -ForegroundColor Cyan
    Write-Host "  1. Backend neu starten:" -ForegroundColor Yellow
    Write-Host "     cd backend"
    Write-Host "     npm run dev"
    Write-Host ""
    Write-Host "  2. ESP32 konfigurieren (in ESP32-Code):" -ForegroundColor Yellow
    Write-Host "     const char* mqtt_server = `"$ip`";"
    Write-Host "     const int mqtt_port = 1883;"
    Write-Host ""
    Write-Host "  3. MQTT Explorer installieren (Optional):" -ForegroundColor Yellow
    Write-Host "     http://mqtt-explorer.com/"
    Write-Host ""
    Write-Host "MQTT testen:" -ForegroundColor Cyan
    Write-Host "  # Terminal 1 (CMD): Subscribe"
    Write-Host "  cd `"$MosquittoPath`""
    Write-Host "  mosquitto_sub.exe -h localhost -t `"grow_monitoring/#`" -v"
    Write-Host ""
    Write-Host "  # Terminal 2 (CMD): Publish"
    Write-Host "  cd `"$MosquittoPath`""
    Write-Host "  mosquitto_pub.exe -h localhost -t `"grow_monitoring/test`" -m `"Hello!`""
    Write-Host ""
    Write-Host "Viel Erfolg! 🌱" -ForegroundColor Green
    Write-Host ""
}

# Hauptprogramm
function Main {
    Write-Info "Starte Installation..."
    Write-Host ""

    # Installation
    Install-Mosquitto
    Configure-Mosquitto
    Start-MosquittoService

    # Firewall
    Add-FirewallRule

    # Tests
    Start-Sleep -Seconds 2
    Test-Port -Port 1883
    Test-Port -Port 9001
    Test-MqttConnection

    # Backend konfigurieren
    Configure-Backend

    # Zusammenfassung
    Show-Summary

    Write-Host ""
    Read-Host "Drücke Enter zum Beenden"
}

# Script ausführen
Main
